<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Zoe</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#constants</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#strings</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#type</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#function-call</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.control.zoe</string>
            <key>match</key>
            <string>\b(import|export|from|as|return|yield|match|with|if|for|implement|return|function|own(ed)?|shared|readonly|take|give|struct|type|enum|let)\b</string>
          </dict>
        </array>
      </dict>
      <key>constants</key>
      <dict>
        <key>name</key>
        <string>constant.zoe</string>
        <key>match</key>
        <string>\b(true|false|(\d+|(\d+)?\.\d+)((i|f)(32|64))?)\b</string>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>/\*</string>
            <key>end</key>
            <string>\*/</string>
            <key>name</key>
            <string>comment.block.zoe</string>
          </dict>
        </array>
      </dict>
      <key>function-call</key>
      <dict>
        <key>begin</key>
        <string>\b(\w+)\(</string>
        <key>end</key>
        <string>\)</string>
        <key>name</key>
        <string>meta.function-call.zoe</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type</string>
          </dict>
        </array>
      </dict>
      <key>type</key>
      <dict>
        <key>name</key>
        <string>entity.name.type.zoe</string>
        <key>match</key>
        <string>\b[A-Z]\w+(\[\])*\b</string>
      </dict>
      <key>strings</key>
      <dict>
        <key>name</key>
        <string>string.quoted.double.zoe</string>
        <key>begin</key>
        <string>"</string>
        <key>end</key>
        <string>"</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape.zoe</string>
            <key>match</key>
            <string>\\.</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.zoe</string>
  </dict>
</plist>