<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Zoe</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#constants</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#strings</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#type</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#function</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#atnames</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.control.zoe</string>
            <key>match</key>
            <string>\b(closure|fn|import|compile|trait|default|try|export|from|as|return|yield|match|with|if|in|else|and|or|for|break|continue|implement|macro|stop|return|function|readonly|struct|type|enum|union|let|const|async|await|lock)\b</string>
          </dict>
        </array>
      </dict>
      <key>constants</key>
      <dict>
        <key>name</key>
        <string>constant.zoe</string>
        <key>match</key>
        <string>\b(null|this|true|false|nothing|(\d+|(\d+)?\.\d+)((i|f)(32|64))?)\b</string>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>#\(\(</string>
            <key>end</key>
            <string>#\)</string>
            <key>name</key>
            <string>comment.block.documentation.zoe</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.md</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>#\(</string>
            <key>end</key>
            <string>#\)</string>
            <key>name</key>
            <string>comment.block.zoe</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>#[^\n]*</string>
            <key>name</key>
            <string>comment.line.double-slash.zoe</string>
          </dict>
        </array>
      </dict>
      <key>function</key>
      <dict>
        <key>match</key>
        <string>\b(\w+)(?=\()</string>
        <key>name</key>
        <string>entity.name.function.zoe</string>
      </dict>
      <key>atnames</key>
      <dict>
        <key>name</key>
        <string>entity.name.tag.zoe</string>
        <key>match</key>
        <string>@\w+</string>
      </dict>
      <key>type</key>
      <dict>
        <key>name</key>
        <string>entity.name.type.zoe</string>
        <key>match</key>
        <string>\b[A-Z]\w*(\[\])*\??</string>
      </dict>
      <key>strings</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>string.quoted.double.zoe</string>
            <key>begin</key>
            <string>"</string>
            <key>end</key>
            <string>"</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>constant.character.escape.zoe</string>
                <key>match</key>
                <string>\\.</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>\$\{</string>
                <key>end</key>
                <string>\}</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.zoe</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>string.quoted.single.zoe</string>
            <key>begin</key>
            <string>'</string>
            <key>end</key>
            <string>'</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>constant.character.escape.zoe</string>
                <key>match</key>
                <string>\\.</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>string.regexp.zoe</string>
            <key>begin</key>
            <string>/</string>
            <key>end</key>
            <string>/[igmu]*</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>constant.character.escape.zoe</string>
                <key>match</key>
                <string>\\.</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>string.quoted.template.zoe</string>
            <key>begin</key>
            <string>`</string>
            <key>end</key>
            <string>`</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>constant.character.escape.zoe</string>
                <key>match</key>
                <string>\\.</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>\$\{</string>
                <key>end</key>
                <string>\}</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.zoe</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.zoe</string>
  </dict>
</plist>